// Auto-generated
let project = new Project('test5');

project.addSources('Sources');
project.addLibrary("C:/Armory_04_win64_b27/Armory/armsdk//armory");
project.addLibrary("C:/Armory_04_win64_b27/Armory/armsdk//iron");
project.addParameter("--macro include('armory.trait')");
project.addParameter("--macro include('armory.trait.internal')");
project.addParameter('armory.trait.internal.DebugConsole');
project.addParameter("--macro keep('armory.trait.internal.DebugConsole')");
project.addShaders('E:/armory tests/build_test5/compiled/Shaders/blur_edge_pass.frag.glsl');
project.addShaders('E:/armory tests/build_test5/compiled/Shaders/compositor_pass.frag.glsl');
project.addShaders('E:/armory tests/build_test5/compiled/Shaders/compositor_pass.vert.glsl');
project.addShaders('E:/armory tests/build_test5/compiled/Shaders/deferred_indirect.frag.glsl');
project.addShaders('E:/armory tests/build_test5/compiled/Shaders/deferred_indirect.vert.glsl');
project.addShaders('E:/armory tests/build_test5/compiled/Shaders/deferred_light.frag.glsl');
project.addShaders('E:/armory tests/build_test5/compiled/Shaders/deferred_light_quad.frag.glsl');
project.addShaders('E:/armory tests/build_test5/compiled/Shaders/pass.vert.glsl');
project.addShaders('E:/armory tests/build_test5/compiled/Shaders/pass_lamp_volume.vert.glsl');
project.addShaders('E:/armory tests/build_test5/compiled/Shaders/pass_viewray.vert.glsl');
project.addShaders('E:/armory tests/build_test5/compiled/Shaders/smaa_blend_weight.frag.glsl');
project.addShaders('E:/armory tests/build_test5/compiled/Shaders/smaa_blend_weight.vert.glsl');
project.addShaders('E:/armory tests/build_test5/compiled/Shaders/smaa_edge_detect.frag.glsl');
project.addShaders('E:/armory tests/build_test5/compiled/Shaders/smaa_edge_detect.vert.glsl');
project.addShaders('E:/armory tests/build_test5/compiled/Shaders/smaa_neighborhood_blend.frag.glsl');
project.addShaders('E:/armory tests/build_test5/compiled/Shaders/smaa_neighborhood_blend.vert.glsl');
project.addShaders('E:/armory tests/build_test5/compiled/Shaders/ssao_pass.frag.glsl');
project.addShaders('E:/armory tests/build_test5/compiled/Shaders/world_pass.frag.glsl');
project.addShaders('E:/armory tests/build_test5/compiled/Shaders/world_pass.vert.glsl');
project.addShaders('build_test5/compiled/Shaders//Compound_material_armskin_mesh.frag.glsl');
project.addShaders('build_test5/compiled/Shaders//Compound_material_armskin_mesh.vert.glsl');
project.addShaders('build_test5/compiled/Shaders//Compound_material_armskin_shadowmap.frag.glsl');
project.addShaders('build_test5/compiled/Shaders//Compound_material_armskin_shadowmap.vert.glsl');
project.addShaders('build_test5/compiled/Shaders//Material_001_mesh.frag.glsl');
project.addShaders('build_test5/compiled/Shaders//Material_001_mesh.vert.glsl');
project.addShaders('build_test5/compiled/Shaders//Material_001_shadowmap.vert.glsl');
project.addAssets("build_test5/compiled/Shaders/Compound_material_armskin_data.arm", { notinlist: true });
project.addAssets("build_test5/compiled/Shaders/Material_001_data.arm", { notinlist: true });
project.addAssets("build_test5/compiled/Shaders/shader_datas.arm", { notinlist: true });
project.addAssets("C:/Armory_04_win64_b27/Armory/armsdk/armory/Assets/brdf.png", { notinlist: true });
project.addAssets("C:/Armory_04_win64_b27/Armory/armsdk/armory/Assets/noise8.png", { notinlist: true });
project.addAssets("C:/Armory_04_win64_b27/Armory/armsdk/armory/Assets/smaa_area.png", { notinlist: true });
project.addAssets("C:/Armory_04_win64_b27/Armory/armsdk/armory/Assets/smaa_search.png", { notinlist: true });
project.addAssets("E:/armory tests/build_test5/compiled/Assets/Scene.arm", { notinlist: true });
project.addAssets("E:/armory tests/build_test5/compiled/Assets/meshes/action_Armature_Default.arm", { notinlist: true });
project.addAssets("E:/armory tests/build_test5/compiled/Assets/meshes/action_Armature_armorypose.arm", { notinlist: true });
project.addAssets("E:/armory tests/build_test5/compiled/Assets/meshes/mesh_Plane.arm", { notinlist: true });
project.addAssets("E:/armory tests/build_test5/compiled/Assets/meshes/mesh__10.001.arm", { notinlist: true });
project.addAssets("build_test5/compiled/Assets/envmaps/World_irradiance.arm", { notinlist: true });
project.addShaders('C:/Armory_04_win64_b27/Armory/armsdk//armory/Shaders/debug_draw/**');
project.addLibrary("C:/Armory_04_win64_b27/Armory/armsdk//lib/zui");
project.addAssets("C:/Armory_04_win64_b27/Armory/armsdk//armory/Assets/droid_sans.ttf", { notinlist: false });
project.addDefine('arm_deferred');
project.addDefine('arm_csm');
project.addDefine('rp_hdr');
project.addDefine('rp_renderer=Deferred');
project.addDefine('rp_depthprepass');
project.addDefine('rp_shadowmap');
project.addDefine('rp_shadowmap_size=1024');
project.addDefine('rp_background=World');
project.addDefine('rp_render_to_texture');
project.addDefine('rp_compositornodes');
project.addDefine('rp_antialiasing=SMAA');
project.addDefine('rp_supersampling=1');
project.addDefine('rp_gi=Off');
project.addDefine('rp_ssgi=SSAO');
project.addDefine('arm_shaderload');
project.addDefine('arm_soundcompress');
project.addDefine('arm_debug');
project.addDefine('arm_ui');
project.addDefine('arm_fast');


resolve(project);
