// Generated by Haxe 3.4.4 (git build master @ 99b08bb)
#include <hxcpp.h>

#ifndef INCLUDED_sys_io_FileSeek
#include <sys/io/FileSeek.h>
#endif
#ifndef INCLUDED_kha_input_SensorType
#include <kha/input/SensorType.h>
#endif
#ifndef INCLUDED_kha_graphics4_VertexData
#include <kha/graphics4/VertexData.h>
#endif
#ifndef INCLUDED_kha_graphics4_Usage
#include <kha/graphics4/Usage.h>
#endif
#ifndef INCLUDED_kha_graphics4_TextureFormat
#include <kha/graphics4/TextureFormat.h>
#endif
#ifndef INCLUDED_kha_graphics4_TextureFilter
#include <kha/graphics4/TextureFilter.h>
#endif
#ifndef INCLUDED_kha_graphics4_TextureAddressing
#include <kha/graphics4/TextureAddressing.h>
#endif
#ifndef INCLUDED_kha_graphics4_TexDir
#include <kha/graphics4/TexDir.h>
#endif
#ifndef INCLUDED_kha_graphics4_StencilAction
#include <kha/graphics4/StencilAction.h>
#endif
#ifndef INCLUDED_kha_graphics4_MipMapFilter
#include <kha/graphics4/MipMapFilter.h>
#endif
#ifndef INCLUDED_kha_graphics4_CullMode
#include <kha/graphics4/CullMode.h>
#endif
#ifndef INCLUDED_kha_graphics4_CompareMode
#include <kha/graphics4/CompareMode.h>
#endif
#ifndef INCLUDED_kha_graphics4_BlendingOperation
#include <kha/graphics4/BlendingOperation.h>
#endif
#ifndef INCLUDED_kha_graphics4_BlendingFactor
#include <kha/graphics4/BlendingFactor.h>
#endif
#ifndef INCLUDED_kha_graphics2_VerTextAlignment
#include <kha/graphics2/VerTextAlignment.h>
#endif
#ifndef INCLUDED_kha_graphics2_ImageScaleQuality
#include <kha/graphics2/ImageScaleQuality.h>
#endif
#ifndef INCLUDED_kha_graphics2_HorTextAlignment
#include <kha/graphics2/HorTextAlignment.h>
#endif
#ifndef INCLUDED_kha_audio2_ogg_vorbis_data_ReaderErrorType
#include <kha/audio2/ogg/vorbis/data/ReaderErrorType.h>
#endif
#ifndef INCLUDED_kha_audio2_ogg_vorbis__VorbisDecodeState_FindPageResult
#include <kha/audio2/ogg/vorbis/_VorbisDecodeState/FindPageResult.h>
#endif
#ifndef INCLUDED_kha_TargetDisplay
#include <kha/TargetDisplay.h>
#endif
#ifndef INCLUDED_kha_Position
#include <kha/Position.h>
#endif
#ifndef INCLUDED_kha_WindowMode
#include <kha/WindowMode.h>
#endif
#ifndef INCLUDED_kha_ScreenRotation
#include <kha/ScreenRotation.h>
#endif
#ifndef INCLUDED_haxe_zip__InflateImpl_State
#include <haxe/zip/_InflateImpl/State.h>
#endif
#ifndef INCLUDED_haxe_zip_Huffman
#include <haxe/zip/Huffman.h>
#endif
#ifndef INCLUDED_haxe_zip_ExtraField
#include <haxe/zip/ExtraField.h>
#endif
#ifndef INCLUDED_haxe_io_Error
#include <haxe/io/Error.h>
#endif
#ifndef INCLUDED_ValueType
#include <ValueType.h>
#endif
#ifndef INCLUDED_kha_vr_VrInterfaceEmulated
#include <kha/vr/VrInterfaceEmulated.h>
#endif
#ifndef INCLUDED_kha_network_SyncBuilder
#include <kha/network/SyncBuilder.h>
#endif
#ifndef INCLUDED_kha_network_Session
#include <kha/network/Session.h>
#endif
#ifndef INCLUDED_kha_network_ControllerBuilder
#include <kha/network/ControllerBuilder.h>
#endif
#ifndef INCLUDED_kha_math_Quaternion
#include <kha/math/Quaternion.h>
#endif
#ifndef INCLUDED_kha_math_Matrix4
#include <kha/math/Matrix4.h>
#endif
#ifndef INCLUDED_kha_math_Matrix3
#include <kha/math/Matrix3.h>
#endif
#ifndef INCLUDED_kha_internal_BytesBlob
#include <kha/internal/BytesBlob.h>
#endif
#ifndef INCLUDED_kha_input_Sensor
#include <kha/input/Sensor.h>
#endif
#ifndef INCLUDED_kha_input_Mouse
#include <kha/input/Mouse.h>
#endif
#ifndef INCLUDED_kha_input_Keyboard
#include <kha/input/Keyboard.h>
#endif
#ifndef INCLUDED_kha_input_Gamepad
#include <kha/input/Gamepad.h>
#endif
#ifndef INCLUDED_kha_graphics4_TextShaderPainter
#include <kha/graphics4/TextShaderPainter.h>
#endif
#ifndef INCLUDED_kha_graphics4_ColoredShaderPainter
#include <kha/graphics4/ColoredShaderPainter.h>
#endif
#ifndef INCLUDED_kha_graphics4_ImageShaderPainter
#include <kha/graphics4/ImageShaderPainter.h>
#endif
#ifndef INCLUDED_kha_graphics2_truetype_StbTruetype
#include <kha/graphics2/truetype/StbTruetype.h>
#endif
#ifndef INCLUDED_kha_graphics2_Graphics
#include <kha/graphics2/Graphics.h>
#endif
#ifndef INCLUDED_kha_audio2_ogg_vorbis_data_Setting
#include <kha/audio2/ogg/vorbis/data/Setting.h>
#endif
#ifndef INCLUDED_kha_audio2_ogg_vorbis_data_PageFlag
#include <kha/audio2/ogg/vorbis/data/PageFlag.h>
#endif
#ifndef INCLUDED_kha_audio2_ogg_vorbis_data_Header
#include <kha/audio2/ogg/vorbis/data/Header.h>
#endif
#ifndef INCLUDED_kha_audio2_ogg_vorbis_data_Codebook
#include <kha/audio2/ogg/vorbis/data/Codebook.h>
#endif
#ifndef INCLUDED_kha_audio2_ogg_vorbis_VorbisTools
#include <kha/audio2/ogg/vorbis/VorbisTools.h>
#endif
#ifndef INCLUDED_kha_audio2_ogg_vorbis_VorbisDecodeState
#include <kha/audio2/ogg/vorbis/VorbisDecodeState.h>
#endif
#ifndef INCLUDED_kha_audio2_ogg_tools_Crc32
#include <kha/audio2/ogg/tools/Crc32.h>
#endif
#ifndef INCLUDED_kha_audio2_Audio1
#include <kha/audio2/Audio1.h>
#endif
#ifndef INCLUDED_kha_SystemImpl
#include <kha/SystemImpl.h>
#endif
#ifndef INCLUDED_kha_System
#include <kha/System.h>
#endif
#ifndef INCLUDED_kha_Shaders
#include <kha/Shaders.h>
#endif
#ifndef INCLUDED_kha_Scheduler
#include <kha/Scheduler.h>
#endif
#ifndef INCLUDED_kha__Color_Color_Impl_
#include <kha/_Color/Color_Impl_.h>
#endif
#ifndef INCLUDED_kha_Assets
#include <kha/Assets.h>
#endif
#ifndef INCLUDED_iron_system_Tween
#include <iron/system/Tween.h>
#endif
#ifndef INCLUDED_iron_system_Time
#include <iron/system/Time.h>
#endif
#ifndef INCLUDED_iron_system_Gamepad
#include <iron/system/Gamepad.h>
#endif
#ifndef INCLUDED_iron_system_Keyboard
#include <iron/system/Keyboard.h>
#endif
#ifndef INCLUDED_iron_system_Pen
#include <iron/system/Pen.h>
#endif
#ifndef INCLUDED_iron_system_Mouse
#include <iron/system/Mouse.h>
#endif
#ifndef INCLUDED_iron_system_Input
#include <iron/system/Input.h>
#endif
#ifndef INCLUDED_iron_object_Uniforms
#include <iron/object/Uniforms.h>
#endif
#ifndef INCLUDED_kha_math_FastMatrix3
#include <kha/math/FastMatrix3.h>
#endif
#ifndef INCLUDED_iron_object_Transform
#include <iron/object/Transform.h>
#endif
#ifndef INCLUDED_iron_object_LampObject
#include <iron/object/LampObject.h>
#endif
#ifndef INCLUDED_iron_object_CameraObject
#include <iron/object/CameraObject.h>
#endif
#ifndef INCLUDED_iron_object_Object
#include <iron/object/Object.h>
#endif
#ifndef INCLUDED_iron_object_BoneAnimation
#include <iron/object/BoneAnimation.h>
#endif
#ifndef INCLUDED_iron_object_Animation
#include <iron/object/Animation.h>
#endif
#ifndef INCLUDED_iron_math_RayCaster
#include <iron/math/RayCaster.h>
#endif
#ifndef INCLUDED_iron_math_Quat
#include <iron/math/Quat.h>
#endif
#ifndef INCLUDED_iron_math_Math
#include <iron/math/Math.h>
#endif
#ifndef INCLUDED_iron_data_WorldData
#include <iron/data/WorldData.h>
#endif
#ifndef INCLUDED_iron_data_ShaderContext
#include <iron/data/ShaderContext.h>
#endif
#ifndef INCLUDED_iron_data_MaterialContext
#include <iron/data/MaterialContext.h>
#endif
#ifndef INCLUDED_iron_data_MaterialData
#include <iron/data/MaterialData.h>
#endif
#ifndef INCLUDED_iron_data_ConstData
#include <iron/data/ConstData.h>
#endif
#ifndef INCLUDED_iron_data_Data
#include <iron/data/Data.h>
#endif
#ifndef INCLUDED_iron_Scene
#include <iron/Scene.h>
#endif
#ifndef INCLUDED_iron_RenderPath
#include <iron/RenderPath.h>
#endif
#ifndef INCLUDED_iron_math_Mat4
#include <iron/math/Mat4.h>
#endif
#ifndef INCLUDED_kha_math_FastMatrix4
#include <kha/math/FastMatrix4.h>
#endif
#ifndef INCLUDED_iron_App
#include <iron/App.h>
#endif
#ifndef INCLUDED_haxe_zip_InflateImpl
#include <haxe/zip/InflateImpl.h>
#endif
#ifndef INCLUDED_haxe_Unserializer
#include <haxe/Unserializer.h>
#endif
#ifndef INCLUDED_haxe_Log
#include <haxe/Log.h>
#endif
#ifndef INCLUDED_armory_trait_internal_MovieTexture
#include <armory/trait/internal/MovieTexture.h>
#endif
#ifndef INCLUDED_armory_trait_WalkNavigation
#include <armory/trait/WalkNavigation.h>
#endif
#ifndef INCLUDED_armory_trait_SimpleScaleObject
#include <armory/trait/SimpleScaleObject.h>
#endif
#ifndef INCLUDED_armory_trait_SimpleRotateObject
#include <armory/trait/SimpleRotateObject.h>
#endif
#ifndef INCLUDED_armory_trait_SimpleMoveObject
#include <armory/trait/SimpleMoveObject.h>
#endif
#ifndef INCLUDED_armory_trait_ConvexBreaker
#include <armory/trait/ConvexBreaker.h>
#endif
#ifndef INCLUDED_armory_trait_NavAgent
#include <armory/trait/NavAgent.h>
#endif
#ifndef INCLUDED_armory_trait_FollowCamera
#include <armory/trait/FollowCamera.h>
#endif
#ifndef INCLUDED_armory_renderpath_RenderPathCreator
#include <armory/renderpath/RenderPathCreator.h>
#endif
#ifndef INCLUDED_armory_data_Config
#include <armory/data/Config.h>
#endif
#ifndef INCLUDED_Main
#include <Main.h>
#endif
#ifndef INCLUDED_sys_io_FileOutput
#include <sys/io/FileOutput.h>
#endif
#ifndef INCLUDED_sys_io_FileInput
#include <sys/io/FileInput.h>
#endif
#ifndef INCLUDED_sys_io_File
#include <sys/io/File.h>
#endif
#ifndef INCLUDED_sys_FileSystem
#include <sys/FileSystem.h>
#endif
#ifndef INCLUDED_kha_vr_VrInterface
#include <kha/vr/VrInterface.h>
#endif
#ifndef INCLUDED_kha_vr_TimeWarpParms
#include <kha/vr/TimeWarpParms.h>
#endif
#ifndef INCLUDED_kha_vr_TimeWarpImage
#include <kha/vr/TimeWarpImage.h>
#endif
#ifndef INCLUDED_kha_vr_SensorState
#include <kha/vr/SensorState.h>
#endif
#ifndef INCLUDED_kha_vr_PoseState
#include <kha/vr/PoseState.h>
#endif
#ifndef INCLUDED_kha_vr_Pose
#include <kha/vr/Pose.h>
#endif
#ifndef INCLUDED_kha_network_State
#include <kha/network/State.h>
#endif
#ifndef INCLUDED_kha_network_Network
#include <kha/network/Network.h>
#endif
#ifndef INCLUDED_kha_network_LocalClient
#include <kha/network/LocalClient.h>
#endif
#ifndef INCLUDED_kha_network_Entity
#include <kha/network/Entity.h>
#endif
#ifndef INCLUDED_kha_network_Client
#include <kha/network/Client.h>
#endif
#ifndef INCLUDED_kha_math_Vector4
#include <kha/math/Vector4.h>
#endif
#ifndef INCLUDED_kha_math_Vector3
#include <kha/math/Vector3.h>
#endif
#ifndef INCLUDED_kha_math_Vector2
#include <kha/math/Vector2.h>
#endif
#ifndef INCLUDED_kha_math_FastVector4
#include <kha/math/FastVector4.h>
#endif
#ifndef INCLUDED_kha_math_FastVector3
#include <kha/math/FastVector3.h>
#endif
#ifndef INCLUDED_kha_math_FastVector2
#include <kha/math/FastVector2.h>
#endif
#ifndef INCLUDED_kha_kore_graphics4_TextureUnit
#include <kha/kore/graphics4/TextureUnit.h>
#endif
#ifndef INCLUDED_kha_kore_graphics4_Graphics2
#include <kha/kore/graphics4/Graphics2.h>
#endif
#ifndef INCLUDED_kha_kore_graphics4_Graphics
#include <kha/kore/graphics4/Graphics.h>
#endif
#ifndef INCLUDED_kha_kore_graphics4_ConstantLocation
#include <kha/kore/graphics4/ConstantLocation.h>
#endif
#ifndef INCLUDED_kha_kore_Video
#include <kha/kore/Video.h>
#endif
#ifndef INCLUDED_kha_kore_Sound
#include <kha/kore/Sound.h>
#endif
#ifndef INCLUDED_kha_kore_Keyboard
#include <kha/kore/Keyboard.h>
#endif
#ifndef INCLUDED_kha_input_Surface
#include <kha/input/Surface.h>
#endif
#ifndef INCLUDED_kha_input_Pen
#include <kha/input/Pen.h>
#endif
#ifndef INCLUDED_kha_input_MouseImpl
#include <kha/input/MouseImpl.h>
#endif
#ifndef INCLUDED_kha_network_Controller
#include <kha/network/Controller.h>
#endif
#ifndef INCLUDED_kha_graphics4_VertexStructure
#include <kha/graphics4/VertexStructure.h>
#endif
#ifndef INCLUDED_kha_graphics4_VertexShader
#include <kha/graphics4/VertexShader.h>
#endif
#ifndef INCLUDED_kha_graphics4_VertexElement
#include <kha/graphics4/VertexElement.h>
#endif
#ifndef INCLUDED_kha_graphics4_VertexBuffer
#include <kha/graphics4/VertexBuffer.h>
#endif
#ifndef INCLUDED_kha_graphics4_TextureUnit
#include <kha/graphics4/TextureUnit.h>
#endif
#ifndef INCLUDED_kha_graphics4_TessellationEvaluationShader
#include <kha/graphics4/TessellationEvaluationShader.h>
#endif
#ifndef INCLUDED_kha_graphics4_TessellationControlShader
#include <kha/graphics4/TessellationControlShader.h>
#endif
#ifndef INCLUDED_kha_graphics4_PipelineState
#include <kha/graphics4/PipelineState.h>
#endif
#ifndef INCLUDED_kha_graphics4_PipelineStateBase
#include <kha/graphics4/PipelineStateBase.h>
#endif
#ifndef INCLUDED_kha_graphics4_IndexBuffer
#include <kha/graphics4/IndexBuffer.h>
#endif
#ifndef INCLUDED_kha_graphics4_Graphics2
#include <kha/graphics4/Graphics2.h>
#endif
#ifndef INCLUDED_kha_graphics4_Graphics
#include <kha/graphics4/Graphics.h>
#endif
#ifndef INCLUDED_kha_graphics4_GeometryShader
#include <kha/graphics4/GeometryShader.h>
#endif
#ifndef INCLUDED_kha_graphics4_FragmentShader
#include <kha/graphics4/FragmentShader.h>
#endif
#ifndef INCLUDED_kha_graphics4_CubeMap
#include <kha/graphics4/CubeMap.h>
#endif
#ifndef INCLUDED_kha_graphics4_ConstantLocation
#include <kha/graphics4/ConstantLocation.h>
#endif
#ifndef INCLUDED_kha_graphics2_truetype_Stbtt__point
#include <kha/graphics2/truetype/Stbtt__point.h>
#endif
#ifndef INCLUDED_kha_graphics2_truetype_Stbtt__active_edge
#include <kha/graphics2/truetype/Stbtt__active_edge.h>
#endif
#ifndef INCLUDED_kha_graphics2_truetype_Stbtt__edge
#include <kha/graphics2/truetype/Stbtt__edge.h>
#endif
#ifndef INCLUDED_kha_graphics2_truetype_Stbtt__bitmap
#include <kha/graphics2/truetype/Stbtt__bitmap.h>
#endif
#ifndef INCLUDED_kha_graphics2_truetype_Stbtt_vertex
#include <kha/graphics2/truetype/Stbtt_vertex.h>
#endif
#ifndef INCLUDED_kha_graphics2_truetype_Stbtt_fontinfo
#include <kha/graphics2/truetype/Stbtt_fontinfo.h>
#endif
#ifndef INCLUDED_kha_graphics2_truetype_Stbtt_pack_context
#include <kha/graphics2/truetype/Stbtt_pack_context.h>
#endif
#ifndef INCLUDED_kha_graphics2_truetype_Stbtt_pack_range
#include <kha/graphics2/truetype/Stbtt_pack_range.h>
#endif
#ifndef INCLUDED_kha_graphics2_truetype_Stbtt_packedchar
#include <kha/graphics2/truetype/Stbtt_packedchar.h>
#endif
#ifndef INCLUDED_kha_graphics2_truetype_Stbtt_aligned_quad
#include <kha/graphics2/truetype/Stbtt_aligned_quad.h>
#endif
#ifndef INCLUDED_kha_graphics2_truetype_Stbtt_bakedchar
#include <kha/graphics2/truetype/Stbtt_bakedchar.h>
#endif
#ifndef INCLUDED_kha_graphics2_truetype_Stbtt_temp_region
#include <kha/graphics2/truetype/Stbtt_temp_region.h>
#endif
#ifndef INCLUDED_kha_graphics2_truetype_Stbtt_temp_font_v_metrics
#include <kha/graphics2/truetype/Stbtt_temp_font_v_metrics.h>
#endif
#ifndef INCLUDED_kha_graphics2_truetype_Stbtt_temp_glyph_h_metrics
#include <kha/graphics2/truetype/Stbtt_temp_glyph_h_metrics.h>
#endif
#ifndef INCLUDED_kha_graphics2_truetype_Stbtt_temp_rect
#include <kha/graphics2/truetype/Stbtt_temp_rect.h>
#endif
#ifndef INCLUDED_kha_graphics2_truetype_VectorOfIntPointer
#include <kha/graphics2/truetype/VectorOfIntPointer.h>
#endif
#ifndef INCLUDED_kha_graphics2_GraphicsExtension
#include <kha/graphics2/GraphicsExtension.h>
#endif
#ifndef INCLUDED_kha_graphics2_Graphics1
#include <kha/graphics2/Graphics1.h>
#endif
#ifndef INCLUDED_kha_graphics1_Graphics
#include <kha/graphics1/Graphics.h>
#endif
#ifndef INCLUDED_kha_compute_TextureUnit
#include <kha/compute/TextureUnit.h>
#endif
#ifndef INCLUDED_kha_compute_Shader
#include <kha/compute/Shader.h>
#endif
#ifndef INCLUDED_kha_compute_ConstantLocation
#include <kha/compute/ConstantLocation.h>
#endif
#ifndef INCLUDED_kha_audio2_ogg_vorbis_data_Residue
#include <kha/audio2/ogg/vorbis/data/Residue.h>
#endif
#ifndef INCLUDED_kha_audio2_ogg_vorbis_data_ReaderError
#include <kha/audio2/ogg/vorbis/data/ReaderError.h>
#endif
#ifndef INCLUDED_kha_audio2_ogg_vorbis_data_ProbedPage
#include <kha/audio2/ogg/vorbis/data/ProbedPage.h>
#endif
#ifndef INCLUDED_kha_audio2_ogg_vorbis_data_Page
#include <kha/audio2/ogg/vorbis/data/Page.h>
#endif
#ifndef INCLUDED_kha_audio2_ogg_vorbis_data_Mode
#include <kha/audio2/ogg/vorbis/data/Mode.h>
#endif
#ifndef INCLUDED_kha_audio2_ogg_vorbis_data_MappingChannel
#include <kha/audio2/ogg/vorbis/data/MappingChannel.h>
#endif
#ifndef INCLUDED_kha_audio2_ogg_vorbis_data_Mapping
#include <kha/audio2/ogg/vorbis/data/Mapping.h>
#endif
#ifndef INCLUDED_kha_audio2_ogg_vorbis_data_IntPoint
#include <kha/audio2/ogg/vorbis/data/IntPoint.h>
#endif
#ifndef INCLUDED_kha_audio2_ogg_vorbis_data_Floor1
#include <kha/audio2/ogg/vorbis/data/Floor1.h>
#endif
#ifndef INCLUDED_kha_audio2_ogg_vorbis_data_Floor0
#include <kha/audio2/ogg/vorbis/data/Floor0.h>
#endif
#ifndef INCLUDED_kha_audio2_ogg_vorbis_data_Floor
#include <kha/audio2/ogg/vorbis/data/Floor.h>
#endif
#ifndef INCLUDED_kha_audio2_ogg_vorbis_data_Comment
#include <kha/audio2/ogg/vorbis/data/Comment.h>
#endif
#ifndef INCLUDED_kha_audio2_ogg_vorbis_VorbisDecoder
#include <kha/audio2/ogg/vorbis/VorbisDecoder.h>
#endif
#ifndef INCLUDED_kha_audio2_ogg_vorbis_Reader
#include <kha/audio2/ogg/vorbis/Reader.h>
#endif
#ifndef INCLUDED_kha_audio2_ogg_tools_Mdct
#include <kha/audio2/ogg/tools/Mdct.h>
#endif
#ifndef INCLUDED_kha_audio2_ogg_tools_MathTools
#include <kha/audio2/ogg/tools/MathTools.h>
#endif
#ifndef INCLUDED_kha_audio2_StreamChannel
#include <kha/audio2/StreamChannel.h>
#endif
#ifndef INCLUDED_kha_audio2_Buffer
#include <kha/audio2/Buffer.h>
#endif
#ifndef INCLUDED_kha_audio2_AudioChannel
#include <kha/audio2/AudioChannel.h>
#endif
#ifndef INCLUDED_kha_audio2_Audio
#include <kha/audio2/Audio.h>
#endif
#ifndef INCLUDED_kha_audio1_AudioChannel
#include <kha/audio1/AudioChannel.h>
#endif
#ifndef INCLUDED_kha_arrays__Uint32Array_Uint32Array_Impl_
#include <kha/arrays/_Uint32Array/Uint32Array_Impl_.h>
#endif
#ifndef INCLUDED_kha_arrays_Uint32ArrayPrivate
#include <kha/arrays/Uint32ArrayPrivate.h>
#endif
#ifndef INCLUDED_kha_arrays__Float32Array_Float32Array_Impl_
#include <kha/arrays/_Float32Array/Float32Array_Impl_.h>
#endif
#ifndef INCLUDED_kha_arrays_Float32ArrayPrivate
#include <kha/arrays/Float32ArrayPrivate.h>
#endif
#ifndef INCLUDED_kha_Worker
#include <kha/Worker.h>
#endif
#ifndef INCLUDED_kha_WindowOptions
#include <kha/WindowOptions.h>
#endif
#ifndef INCLUDED_kha_WindowedModeOptions
#include <kha/WindowedModeOptions.h>
#endif
#ifndef INCLUDED_kha_RendererOptions
#include <kha/RendererOptions.h>
#endif
#ifndef INCLUDED_kha_Video
#include <kha/Video.h>
#endif
#ifndef INCLUDED_kha__SuperString_SuperString_Impl_
#include <kha/_SuperString/SuperString_Impl_.h>
#endif
#ifndef INCLUDED_kha_Sound
#include <kha/Sound.h>
#endif
#ifndef INCLUDED_kha_FrameTask
#include <kha/FrameTask.h>
#endif
#ifndef INCLUDED_kha_TimeTask
#include <kha/TimeTask.h>
#endif
#ifndef INCLUDED_kha_LoaderImpl
#include <kha/LoaderImpl.h>
#endif
#ifndef INCLUDED_kha_Kravur
#include <kha/Kravur.h>
#endif
#ifndef INCLUDED_kha_KravurImage
#include <kha/KravurImage.h>
#endif
#ifndef INCLUDED_kha_AlignedQuad
#include <kha/AlignedQuad.h>
#endif
#ifndef INCLUDED_kha_Image
#include <kha/Image.h>
#endif
#ifndef INCLUDED_kha_Resource
#include <kha/Resource.h>
#endif
#ifndef INCLUDED_kha_Framebuffer
#include <kha/Framebuffer.h>
#endif
#ifndef INCLUDED_kha_DisplayImpl
#include <kha/DisplayImpl.h>
#endif
#ifndef INCLUDED_kha_Display
#include <kha/Display.h>
#endif
#ifndef INCLUDED_kha_Canvas
#include <kha/Canvas.h>
#endif
#ifndef INCLUDED_kha__Assets_VideoList
#include <kha/_Assets/VideoList.h>
#endif
#ifndef INCLUDED_kha__Assets_FontList
#include <kha/_Assets/FontList.h>
#endif
#ifndef INCLUDED_kha__Assets_BlobList
#include <kha/_Assets/BlobList.h>
#endif
#ifndef INCLUDED_kha__Assets_SoundList
#include <kha/_Assets/SoundList.h>
#endif
#ifndef INCLUDED_kha__Assets_ImageList
#include <kha/_Assets/ImageList.h>
#endif
#ifndef INCLUDED_iron_system_Sensor
#include <iron/system/Sensor.h>
#endif
#ifndef INCLUDED_iron_system_GamepadStick
#include <iron/system/GamepadStick.h>
#endif
#ifndef INCLUDED_iron_system_VirtualInput
#include <iron/system/VirtualInput.h>
#endif
#ifndef INCLUDED_iron_system_VirtualButton
#include <iron/system/VirtualButton.h>
#endif
#ifndef INCLUDED_iron_system_Audio
#include <iron/system/Audio.h>
#endif
#ifndef INCLUDED_iron_system_ArmPack
#include <iron/system/ArmPack.h>
#endif
#ifndef INCLUDED_iron_object_Tilesheet
#include <iron/object/Tilesheet.h>
#endif
#ifndef INCLUDED_iron_object_SpeakerObject
#include <iron/object/SpeakerObject.h>
#endif
#ifndef INCLUDED_iron_object_Particle
#include <iron/object/Particle.h>
#endif
#ifndef INCLUDED_iron_object_ParticleSystem
#include <iron/object/ParticleSystem.h>
#endif
#ifndef INCLUDED_iron_object_ObjectAnimation
#include <iron/object/ObjectAnimation.h>
#endif
#ifndef INCLUDED_iron_object_MeshObject
#include <iron/object/MeshObject.h>
#endif
#ifndef INCLUDED_iron_object_DecalObject
#include <iron/object/DecalObject.h>
#endif
#ifndef INCLUDED_iron_object_Constraint
#include <iron/object/Constraint.h>
#endif
#ifndef INCLUDED_iron_object_FrustumPlane
#include <iron/object/FrustumPlane.h>
#endif
#ifndef INCLUDED_iron_math_Vec2
#include <iron/math/Vec2.h>
#endif
#ifndef INCLUDED_iron_math_Plane
#include <iron/math/Plane.h>
#endif
#ifndef INCLUDED_iron_math_Ray
#include <iron/math/Ray.h>
#endif
#ifndef INCLUDED_iron_math_Mat3
#include <iron/math/Mat3.h>
#endif
#ifndef INCLUDED_iron_data_Probe
#include <iron/data/Probe.h>
#endif
#ifndef INCLUDED_iron_data_ShaderData
#include <iron/data/ShaderData.h>
#endif
#ifndef INCLUDED_iron_data_SceneStream
#include <iron/data/SceneStream.h>
#endif
#ifndef INCLUDED_iron_data_StreamSector
#include <iron/data/StreamSector.h>
#endif
#ifndef INCLUDED_iron_data_ParticleData
#include <iron/data/ParticleData.h>
#endif
#ifndef INCLUDED_iron_data_MeshData
#include <iron/data/MeshData.h>
#endif
#ifndef INCLUDED_iron_data_Bucket
#include <iron/data/Bucket.h>
#endif
#ifndef INCLUDED_iron_data_MeshBatch
#include <iron/data/MeshBatch.h>
#endif
#ifndef INCLUDED_iron_data_LampData
#include <iron/data/LampData.h>
#endif
#ifndef INCLUDED_iron_data_Geometry
#include <iron/data/Geometry.h>
#endif
#ifndef INCLUDED_iron_data_CameraData
#include <iron/data/CameraData.h>
#endif
#ifndef INCLUDED_iron_data_Armature
#include <iron/data/Armature.h>
#endif
#ifndef INCLUDED_iron_CachedShaderContext
#include <iron/CachedShaderContext.h>
#endif
#ifndef INCLUDED_iron_RenderTarget
#include <iron/RenderTarget.h>
#endif
#ifndef INCLUDED_iron_RenderTargetRaw
#include <iron/RenderTargetRaw.h>
#endif
#ifndef INCLUDED_iron_math_Vec4
#include <iron/math/Vec4.h>
#endif
#ifndef INCLUDED_haxe_zip_Uncompress
#include <haxe/zip/Uncompress.h>
#endif
#ifndef INCLUDED_haxe_zip_Reader
#include <haxe/zip/Reader.h>
#endif
#ifndef INCLUDED_haxe_zip__InflateImpl_Window
#include <haxe/zip/_InflateImpl/Window.h>
#endif
#ifndef INCLUDED_haxe_zip_HuffTools
#include <haxe/zip/HuffTools.h>
#endif
#ifndef INCLUDED_haxe_io_Path
#include <haxe/io/Path.h>
#endif
#ifndef INCLUDED_haxe_io_FPHelper
#include <haxe/io/FPHelper.h>
#endif
#ifndef INCLUDED_haxe_io_Eof
#include <haxe/io/Eof.h>
#endif
#ifndef INCLUDED_haxe_io_BytesOutput
#include <haxe/io/BytesOutput.h>
#endif
#ifndef INCLUDED_haxe_io_Output
#include <haxe/io/Output.h>
#endif
#ifndef INCLUDED_haxe_io_BytesInput
#include <haxe/io/BytesInput.h>
#endif
#ifndef INCLUDED_haxe_io_Input
#include <haxe/io/Input.h>
#endif
#ifndef INCLUDED_haxe_io_BytesBuffer
#include <haxe/io/BytesBuffer.h>
#endif
#ifndef INCLUDED_haxe_io_Bytes
#include <haxe/io/Bytes.h>
#endif
#ifndef INCLUDED_haxe_format_JsonPrinter
#include <haxe/format/JsonPrinter.h>
#endif
#ifndef INCLUDED_haxe_format_JsonParser
#include <haxe/format/JsonParser.h>
#endif
#ifndef INCLUDED_haxe_ds_StringMap
#include <haxe/ds/StringMap.h>
#endif
#ifndef INCLUDED_haxe_ds_ObjectMap
#include <haxe/ds/ObjectMap.h>
#endif
#ifndef INCLUDED_haxe_ds_IntMap
#include <haxe/ds/IntMap.h>
#endif
#ifndef INCLUDED_haxe_crypto_Adler32
#include <haxe/crypto/Adler32.h>
#endif
#ifndef INCLUDED_haxe_Utf8
#include <haxe/Utf8.h>
#endif
#ifndef INCLUDED_haxe__Unserializer_DefaultResolver
#include <haxe/_Unserializer/DefaultResolver.h>
#endif
#ifndef INCLUDED_haxe_IMap
#include <haxe/IMap.h>
#endif
#ifndef INCLUDED_cpp_vm_Thread
#include <cpp/vm/Thread.h>
#endif
#ifndef INCLUDED_cpp_vm_Mutex
#include <cpp/vm/Mutex.h>
#endif
#ifndef INCLUDED_armory_trait_physics_SoftBody
#include <armory/trait/physics/SoftBody.h>
#endif
#ifndef INCLUDED_armory_trait_physics_RigidBody
#include <armory/trait/physics/RigidBody.h>
#endif
#ifndef INCLUDED_armory_trait_physics_PhysicsWorld
#include <armory/trait/physics/PhysicsWorld.h>
#endif
#ifndef INCLUDED_armory_trait_physics_PhysicsHook
#include <armory/trait/physics/PhysicsHook.h>
#endif
#ifndef INCLUDED_armory_trait_physics_PhysicsConstraint
#include <armory/trait/physics/PhysicsConstraint.h>
#endif
#ifndef INCLUDED_armory_trait_physics_KinematicCharacterController
#include <armory/trait/physics/KinematicCharacterController.h>
#endif
#ifndef INCLUDED_armory_trait_navigation_Navigation
#include <armory/trait/navigation/Navigation.h>
#endif
#ifndef INCLUDED_armory_trait_internal_LoadingScreen
#include <armory/trait/internal/LoadingScreen.h>
#endif
#ifndef INCLUDED_armory_trait_internal_DebugConsole
#include <armory/trait/internal/DebugConsole.h>
#endif
#ifndef INCLUDED_armory_trait_internal_CanvasScript
#include <armory/trait/internal/CanvasScript.h>
#endif
#ifndef INCLUDED_armory_trait_VirtualGamepad
#include <armory/trait/VirtualGamepad.h>
#endif
#ifndef INCLUDED_armory_trait_VehicleWheel
#include <armory/trait/VehicleWheel.h>
#endif
#ifndef INCLUDED_armory_trait_VehicleBody
#include <armory/trait/VehicleBody.h>
#endif
#ifndef INCLUDED_armory_trait_VRNavigation
#include <armory/trait/VRNavigation.h>
#endif
#ifndef INCLUDED_armory_trait_ThirdPersonController
#include <armory/trait/ThirdPersonController.h>
#endif
#ifndef INCLUDED_armory_trait_SidescrollerController
#include <armory/trait/SidescrollerController.h>
#endif
#ifndef INCLUDED_armory_trait_SceneInstance
#include <armory/trait/SceneInstance.h>
#endif
#ifndef INCLUDED_armory_trait_PhysicsDrag
#include <armory/trait/PhysicsDrag.h>
#endif
#ifndef INCLUDED_armory_trait_Face3
#include <armory/trait/Face3.h>
#endif
#ifndef INCLUDED_armory_trait_ConvexHull
#include <armory/trait/ConvexHull.h>
#endif
#ifndef INCLUDED_armory_trait_Plane
#include <armory/trait/Plane.h>
#endif
#ifndef INCLUDED_armory_trait_Line3
#include <armory/trait/Line3.h>
#endif
#ifndef INCLUDED_armory_trait_CutResult
#include <armory/trait/CutResult.h>
#endif
#ifndef INCLUDED_armory_trait_UserData
#include <armory/trait/UserData.h>
#endif
#ifndef INCLUDED_armory_trait_PhysicsBreak
#include <armory/trait/PhysicsBreak.h>
#endif
#ifndef INCLUDED_armory_trait_NavMesh
#include <armory/trait/NavMesh.h>
#endif
#ifndef INCLUDED_armory_trait_NavCrowd
#include <armory/trait/NavCrowd.h>
#endif
#ifndef INCLUDED_armory_trait_Macro
#include <armory/trait/Macro.h>
#endif
#ifndef INCLUDED_armory_trait_FirstPersonController
#include <armory/trait/FirstPersonController.h>
#endif
#ifndef INCLUDED_armory_trait_internal_CameraController
#include <armory/trait/internal/CameraController.h>
#endif
#ifndef INCLUDED_armory_trait_Character
#include <armory/trait/Character.h>
#endif
#ifndef INCLUDED_armory_trait_CameraTexture
#include <armory/trait/CameraTexture.h>
#endif
#ifndef INCLUDED_armory_trait_ArcBall
#include <armory/trait/ArcBall.h>
#endif
#ifndef INCLUDED_iron_Trait
#include <iron/Trait.h>
#endif
#ifndef INCLUDED_armory_renderpath_RenderPathDeferred
#include <armory/renderpath/RenderPathDeferred.h>
#endif
#ifndef INCLUDED_armory_renderpath_Inc
#include <armory/renderpath/Inc.h>
#endif
#ifndef INCLUDED_armory_object_Uniforms
#include <armory/object/Uniforms.h>
#endif
#ifndef INCLUDED_Type
#include <Type.h>
#endif
#ifndef INCLUDED_StringTools
#include <StringTools.h>
#endif
#ifndef INCLUDED_StringBuf
#include <StringBuf.h>
#endif
#ifndef INCLUDED_Std
#include <Std.h>
#endif
#ifndef INCLUDED_Reflect
#include <Reflect.h>
#endif
#ifndef INCLUDED__List_ListIterator
#include <_List/ListIterator.h>
#endif
#ifndef INCLUDED__List_ListNode
#include <_List/ListNode.h>
#endif
#ifndef INCLUDED_List
#include <List.h>
#endif
#ifndef INCLUDED_Lambda
#include <Lambda.h>
#endif
#ifndef INCLUDED_Date
#include <Date.h>
#endif

void __files__boot();

void __boot_all()
{
__files__boot();
hx::RegisterResources( hx::GetResources() );
::sys::io::FileSeek_obj::__register();
::kha::input::SensorType_obj::__register();
::kha::graphics4::VertexData_obj::__register();
::kha::graphics4::Usage_obj::__register();
::kha::graphics4::TextureFormat_obj::__register();
::kha::graphics4::TextureFilter_obj::__register();
::kha::graphics4::TextureAddressing_obj::__register();
::kha::graphics4::TexDir_obj::__register();
::kha::graphics4::StencilAction_obj::__register();
::kha::graphics4::MipMapFilter_obj::__register();
::kha::graphics4::CullMode_obj::__register();
::kha::graphics4::CompareMode_obj::__register();
::kha::graphics4::BlendingOperation_obj::__register();
::kha::graphics4::BlendingFactor_obj::__register();
::kha::graphics2::VerTextAlignment_obj::__register();
::kha::graphics2::ImageScaleQuality_obj::__register();
::kha::graphics2::HorTextAlignment_obj::__register();
::kha::audio2::ogg::vorbis::data::ReaderErrorType_obj::__register();
::kha::audio2::ogg::vorbis::_VorbisDecodeState::FindPageResult_obj::__register();
::kha::TargetDisplay_obj::__register();
::kha::Position_obj::__register();
::kha::WindowMode_obj::__register();
::kha::ScreenRotation_obj::__register();
::haxe::zip::_InflateImpl::State_obj::__register();
::haxe::zip::Huffman_obj::__register();
::haxe::zip::ExtraField_obj::__register();
::haxe::io::Error_obj::__register();
::ValueType_obj::__register();
::kha::vr::VrInterfaceEmulated_obj::__register();
::kha::network::SyncBuilder_obj::__register();
::kha::network::Session_obj::__register();
::kha::network::ControllerBuilder_obj::__register();
::kha::math::Quaternion_obj::__register();
::kha::math::Matrix4_obj::__register();
::kha::math::Matrix3_obj::__register();
::kha::internal::BytesBlob_obj::__register();
::kha::input::Sensor_obj::__register();
::kha::input::Mouse_obj::__register();
::kha::input::Keyboard_obj::__register();
::kha::input::Gamepad_obj::__register();
::kha::graphics4::TextShaderPainter_obj::__register();
::kha::graphics4::ColoredShaderPainter_obj::__register();
::kha::graphics4::ImageShaderPainter_obj::__register();
::kha::graphics2::truetype::StbTruetype_obj::__register();
::kha::graphics2::Graphics_obj::__register();
::kha::audio2::ogg::vorbis::data::Setting_obj::__register();
::kha::audio2::ogg::vorbis::data::PageFlag_obj::__register();
::kha::audio2::ogg::vorbis::data::Header_obj::__register();
::kha::audio2::ogg::vorbis::data::Codebook_obj::__register();
::kha::audio2::ogg::vorbis::VorbisTools_obj::__register();
::kha::audio2::ogg::vorbis::VorbisDecodeState_obj::__register();
::kha::audio2::ogg::tools::Crc32_obj::__register();
::kha::audio2::Audio1_obj::__register();
::kha::SystemImpl_obj::__register();
::kha::System_obj::__register();
::kha::Shaders_obj::__register();
::kha::Scheduler_obj::__register();
::kha::_Color::Color_Impl__obj::__register();
::kha::Assets_obj::__register();
::iron::_hx_system::Tween_obj::__register();
::iron::_hx_system::Time_obj::__register();
::iron::_hx_system::Gamepad_obj::__register();
::iron::_hx_system::Keyboard_obj::__register();
::iron::_hx_system::Pen_obj::__register();
::iron::_hx_system::Mouse_obj::__register();
::iron::_hx_system::Input_obj::__register();
::iron::object::Uniforms_obj::__register();
::kha::math::FastMatrix3_obj::__register();
::iron::object::Transform_obj::__register();
::iron::object::LampObject_obj::__register();
::iron::object::CameraObject_obj::__register();
::iron::object::Object_obj::__register();
::iron::object::BoneAnimation_obj::__register();
::iron::object::Animation_obj::__register();
::iron::math::RayCaster_obj::__register();
::iron::math::Quat_obj::__register();
::iron::math::Math_obj::__register();
::iron::data::WorldData_obj::__register();
::iron::data::ShaderContext_obj::__register();
::iron::data::MaterialContext_obj::__register();
::iron::data::MaterialData_obj::__register();
::iron::data::ConstData_obj::__register();
::iron::data::Data_obj::__register();
::iron::Scene_obj::__register();
::iron::RenderPath_obj::__register();
::iron::math::Mat4_obj::__register();
::kha::math::FastMatrix4_obj::__register();
::iron::App_obj::__register();
::haxe::zip::InflateImpl_obj::__register();
::haxe::Unserializer_obj::__register();
::haxe::Log_obj::__register();
::armory::trait::internal::MovieTexture_obj::__register();
::armory::trait::WalkNavigation_obj::__register();
::armory::trait::SimpleScaleObject_obj::__register();
::armory::trait::SimpleRotateObject_obj::__register();
::armory::trait::SimpleMoveObject_obj::__register();
::armory::trait::ConvexBreaker_obj::__register();
::armory::trait::NavAgent_obj::__register();
::armory::trait::FollowCamera_obj::__register();
::armory::renderpath::RenderPathCreator_obj::__register();
::armory::data::Config_obj::__register();
::Main_obj::__register();
::sys::io::FileOutput_obj::__register();
::sys::io::FileInput_obj::__register();
::sys::io::File_obj::__register();
::sys::FileSystem_obj::__register();
::kha::vr::VrInterface_obj::__register();
::kha::vr::TimeWarpParms_obj::__register();
::kha::vr::TimeWarpImage_obj::__register();
::kha::vr::SensorState_obj::__register();
::kha::vr::PoseState_obj::__register();
::kha::vr::Pose_obj::__register();
::kha::network::State_obj::__register();
::kha::network::Network_obj::__register();
::kha::network::LocalClient_obj::__register();
::kha::network::Entity_obj::__register();
::kha::network::Client_obj::__register();
::kha::math::Vector4_obj::__register();
::kha::math::Vector3_obj::__register();
::kha::math::Vector2_obj::__register();
::kha::math::FastVector4_obj::__register();
::kha::math::FastVector3_obj::__register();
::kha::math::FastVector2_obj::__register();
::kha::kore::graphics4::TextureUnit_obj::__register();
::kha::kore::graphics4::Graphics2_obj::__register();
::kha::kore::graphics4::Graphics_obj::__register();
::kha::kore::graphics4::ConstantLocation_obj::__register();
::kha::kore::Video_obj::__register();
::kha::kore::Sound_obj::__register();
::kha::kore::Keyboard_obj::__register();
::kha::input::Surface_obj::__register();
::kha::input::Pen_obj::__register();
::kha::input::MouseImpl_obj::__register();
::kha::network::Controller_obj::__register();
::kha::graphics4::VertexStructure_obj::__register();
::kha::graphics4::VertexShader_obj::__register();
::kha::graphics4::VertexElement_obj::__register();
::kha::graphics4::VertexBuffer_obj::__register();
::kha::graphics4::TextureUnit_obj::__register();
::kha::graphics4::TessellationEvaluationShader_obj::__register();
::kha::graphics4::TessellationControlShader_obj::__register();
::kha::graphics4::PipelineState_obj::__register();
::kha::graphics4::PipelineStateBase_obj::__register();
::kha::graphics4::IndexBuffer_obj::__register();
::kha::graphics4::Graphics2_obj::__register();
::kha::graphics4::Graphics_obj::__register();
::kha::graphics4::GeometryShader_obj::__register();
::kha::graphics4::FragmentShader_obj::__register();
::kha::graphics4::CubeMap_obj::__register();
::kha::graphics4::ConstantLocation_obj::__register();
::kha::graphics2::truetype::Stbtt__point_obj::__register();
::kha::graphics2::truetype::Stbtt__active_edge_obj::__register();
::kha::graphics2::truetype::Stbtt__edge_obj::__register();
::kha::graphics2::truetype::Stbtt__bitmap_obj::__register();
::kha::graphics2::truetype::Stbtt_vertex_obj::__register();
::kha::graphics2::truetype::Stbtt_fontinfo_obj::__register();
::kha::graphics2::truetype::Stbtt_pack_context_obj::__register();
::kha::graphics2::truetype::Stbtt_pack_range_obj::__register();
::kha::graphics2::truetype::Stbtt_packedchar_obj::__register();
::kha::graphics2::truetype::Stbtt_aligned_quad_obj::__register();
::kha::graphics2::truetype::Stbtt_bakedchar_obj::__register();
::kha::graphics2::truetype::Stbtt_temp_region_obj::__register();
::kha::graphics2::truetype::Stbtt_temp_font_v_metrics_obj::__register();
::kha::graphics2::truetype::Stbtt_temp_glyph_h_metrics_obj::__register();
::kha::graphics2::truetype::Stbtt_temp_rect_obj::__register();
::kha::graphics2::truetype::VectorOfIntPointer_obj::__register();
::kha::graphics2::GraphicsExtension_obj::__register();
::kha::graphics2::Graphics1_obj::__register();
::kha::graphics1::Graphics_obj::__register();
::kha::compute::TextureUnit_obj::__register();
::kha::compute::Shader_obj::__register();
::kha::compute::ConstantLocation_obj::__register();
::kha::audio2::ogg::vorbis::data::Residue_obj::__register();
::kha::audio2::ogg::vorbis::data::ReaderError_obj::__register();
::kha::audio2::ogg::vorbis::data::ProbedPage_obj::__register();
::kha::audio2::ogg::vorbis::data::Page_obj::__register();
::kha::audio2::ogg::vorbis::data::Mode_obj::__register();
::kha::audio2::ogg::vorbis::data::MappingChannel_obj::__register();
::kha::audio2::ogg::vorbis::data::Mapping_obj::__register();
::kha::audio2::ogg::vorbis::data::IntPoint_obj::__register();
::kha::audio2::ogg::vorbis::data::Floor1_obj::__register();
::kha::audio2::ogg::vorbis::data::Floor0_obj::__register();
::kha::audio2::ogg::vorbis::data::Floor_obj::__register();
::kha::audio2::ogg::vorbis::data::Comment_obj::__register();
::kha::audio2::ogg::vorbis::VorbisDecoder_obj::__register();
::kha::audio2::ogg::vorbis::Reader_obj::__register();
::kha::audio2::ogg::tools::Mdct_obj::__register();
::kha::audio2::ogg::tools::MathTools_obj::__register();
::kha::audio2::StreamChannel_obj::__register();
::kha::audio2::Buffer_obj::__register();
::kha::audio2::AudioChannel_obj::__register();
::kha::audio2::Audio_obj::__register();
::kha::audio1::AudioChannel_obj::__register();
::kha::arrays::_Uint32Array::Uint32Array_Impl__obj::__register();
::kha::arrays::Uint32ArrayPrivate_obj::__register();
::kha::arrays::_Float32Array::Float32Array_Impl__obj::__register();
::kha::arrays::Float32ArrayPrivate_obj::__register();
::kha::Worker_obj::__register();
::kha::WindowOptions_obj::__register();
::kha::WindowedModeOptions_obj::__register();
::kha::RendererOptions_obj::__register();
::kha::Video_obj::__register();
::kha::_SuperString::SuperString_Impl__obj::__register();
::kha::Sound_obj::__register();
::kha::FrameTask_obj::__register();
::kha::TimeTask_obj::__register();
::kha::LoaderImpl_obj::__register();
::kha::Kravur_obj::__register();
::kha::KravurImage_obj::__register();
::kha::AlignedQuad_obj::__register();
::kha::Image_obj::__register();
::kha::Resource_obj::__register();
::kha::Framebuffer_obj::__register();
::kha::DisplayImpl_obj::__register();
::kha::Display_obj::__register();
::kha::Canvas_obj::__register();
::kha::_Assets::VideoList_obj::__register();
::kha::_Assets::FontList_obj::__register();
::kha::_Assets::BlobList_obj::__register();
::kha::_Assets::SoundList_obj::__register();
::kha::_Assets::ImageList_obj::__register();
::iron::_hx_system::Sensor_obj::__register();
::iron::_hx_system::GamepadStick_obj::__register();
::iron::_hx_system::VirtualInput_obj::__register();
::iron::_hx_system::VirtualButton_obj::__register();
::iron::_hx_system::Audio_obj::__register();
::iron::_hx_system::ArmPack_obj::__register();
::iron::object::Tilesheet_obj::__register();
::iron::object::SpeakerObject_obj::__register();
::iron::object::Particle_obj::__register();
::iron::object::ParticleSystem_obj::__register();
::iron::object::ObjectAnimation_obj::__register();
::iron::object::MeshObject_obj::__register();
::iron::object::DecalObject_obj::__register();
::iron::object::Constraint_obj::__register();
::iron::object::FrustumPlane_obj::__register();
::iron::math::Vec2_obj::__register();
::iron::math::Plane_obj::__register();
::iron::math::Ray_obj::__register();
::iron::math::Mat3_obj::__register();
::iron::data::Probe_obj::__register();
::iron::data::ShaderData_obj::__register();
::iron::data::SceneStream_obj::__register();
::iron::data::StreamSector_obj::__register();
::iron::data::ParticleData_obj::__register();
::iron::data::MeshData_obj::__register();
::iron::data::Bucket_obj::__register();
::iron::data::MeshBatch_obj::__register();
::iron::data::LampData_obj::__register();
::iron::data::Geometry_obj::__register();
::iron::data::CameraData_obj::__register();
::iron::data::Armature_obj::__register();
::iron::CachedShaderContext_obj::__register();
::iron::RenderTarget_obj::__register();
::iron::RenderTargetRaw_obj::__register();
::iron::math::Vec4_obj::__register();
::haxe::zip::Uncompress_obj::__register();
::haxe::zip::Reader_obj::__register();
::haxe::zip::_InflateImpl::Window_obj::__register();
::haxe::zip::HuffTools_obj::__register();
::haxe::io::Path_obj::__register();
::haxe::io::FPHelper_obj::__register();
::haxe::io::Eof_obj::__register();
::haxe::io::BytesOutput_obj::__register();
::haxe::io::Output_obj::__register();
::haxe::io::BytesInput_obj::__register();
::haxe::io::Input_obj::__register();
::haxe::io::BytesBuffer_obj::__register();
::haxe::io::Bytes_obj::__register();
::haxe::format::JsonPrinter_obj::__register();
::haxe::format::JsonParser_obj::__register();
::haxe::ds::StringMap_obj::__register();
::haxe::ds::ObjectMap_obj::__register();
::haxe::ds::IntMap_obj::__register();
::haxe::crypto::Adler32_obj::__register();
::haxe::Utf8_obj::__register();
::haxe::_Unserializer::DefaultResolver_obj::__register();
::haxe::IMap_obj::__register();
::cpp::vm::Thread_obj::__register();
::cpp::vm::Mutex_obj::__register();
::armory::trait::physics::SoftBody_obj::__register();
::armory::trait::physics::RigidBody_obj::__register();
::armory::trait::physics::PhysicsWorld_obj::__register();
::armory::trait::physics::PhysicsHook_obj::__register();
::armory::trait::physics::PhysicsConstraint_obj::__register();
::armory::trait::physics::KinematicCharacterController_obj::__register();
::armory::trait::navigation::Navigation_obj::__register();
::armory::trait::internal::LoadingScreen_obj::__register();
::armory::trait::internal::DebugConsole_obj::__register();
::armory::trait::internal::CanvasScript_obj::__register();
::armory::trait::VirtualGamepad_obj::__register();
::armory::trait::VehicleWheel_obj::__register();
::armory::trait::VehicleBody_obj::__register();
::armory::trait::VRNavigation_obj::__register();
::armory::trait::ThirdPersonController_obj::__register();
::armory::trait::SidescrollerController_obj::__register();
::armory::trait::SceneInstance_obj::__register();
::armory::trait::PhysicsDrag_obj::__register();
::armory::trait::Face3_obj::__register();
::armory::trait::ConvexHull_obj::__register();
::armory::trait::Plane_obj::__register();
::armory::trait::Line3_obj::__register();
::armory::trait::CutResult_obj::__register();
::armory::trait::UserData_obj::__register();
::armory::trait::PhysicsBreak_obj::__register();
::armory::trait::NavMesh_obj::__register();
::armory::trait::NavCrowd_obj::__register();
::armory::trait::Macro_obj::__register();
::armory::trait::FirstPersonController_obj::__register();
::armory::trait::internal::CameraController_obj::__register();
::armory::trait::Character_obj::__register();
::armory::trait::CameraTexture_obj::__register();
::armory::trait::ArcBall_obj::__register();
::iron::Trait_obj::__register();
::armory::renderpath::RenderPathDeferred_obj::__register();
::armory::renderpath::Inc_obj::__register();
::armory::object::Uniforms_obj::__register();
::Type_obj::__register();
::StringTools_obj::__register();
::StringBuf_obj::__register();
::Std_obj::__register();
::Reflect_obj::__register();
::_List::ListIterator_obj::__register();
::_List::ListNode_obj::__register();
::List_obj::__register();
::Lambda_obj::__register();
::Date_obj::__register();
::sys::io::FileSeek_obj::__boot();
::kha::input::SensorType_obj::__boot();
::kha::graphics4::VertexData_obj::__boot();
::kha::graphics4::Usage_obj::__boot();
::kha::graphics4::TextureFormat_obj::__boot();
::kha::graphics4::TextureFilter_obj::__boot();
::kha::graphics4::TextureAddressing_obj::__boot();
::kha::graphics4::TexDir_obj::__boot();
::kha::graphics4::StencilAction_obj::__boot();
::kha::graphics4::MipMapFilter_obj::__boot();
::kha::graphics4::CullMode_obj::__boot();
::kha::graphics4::CompareMode_obj::__boot();
::kha::graphics4::BlendingOperation_obj::__boot();
::kha::graphics4::BlendingFactor_obj::__boot();
::kha::graphics2::VerTextAlignment_obj::__boot();
::kha::graphics2::ImageScaleQuality_obj::__boot();
::kha::graphics2::HorTextAlignment_obj::__boot();
::kha::audio2::ogg::vorbis::data::ReaderErrorType_obj::__boot();
::kha::audio2::ogg::vorbis::_VorbisDecodeState::FindPageResult_obj::__boot();
::kha::TargetDisplay_obj::__boot();
::kha::Position_obj::__boot();
::kha::WindowMode_obj::__boot();
::kha::ScreenRotation_obj::__boot();
::haxe::zip::_InflateImpl::State_obj::__boot();
::haxe::zip::Huffman_obj::__boot();
::haxe::zip::ExtraField_obj::__boot();
::haxe::io::Error_obj::__boot();
::ValueType_obj::__boot();
::haxe::Log_obj::__boot();
::Main_obj::__boot();
::armory::data::Config_obj::__boot();
::armory::renderpath::RenderPathCreator_obj::__boot();
::armory::trait::FollowCamera_obj::__boot();
::armory::trait::NavAgent_obj::__boot();
::armory::trait::ConvexBreaker_obj::__boot();
::armory::trait::SimpleMoveObject_obj::__boot();
::armory::trait::SimpleRotateObject_obj::__boot();
::armory::trait::SimpleScaleObject_obj::__boot();
::armory::trait::WalkNavigation_obj::__boot();
::armory::trait::internal::MovieTexture_obj::__boot();
::haxe::Unserializer_obj::__boot();
::haxe::zip::InflateImpl_obj::__boot();
::iron::App_obj::__boot();
::kha::math::FastMatrix4_obj::__boot();
::iron::math::Mat4_obj::__boot();
::iron::RenderPath_obj::__boot();
::iron::Scene_obj::__boot();
::iron::data::Data_obj::__boot();
::iron::data::ConstData_obj::__boot();
::iron::data::MaterialData_obj::__boot();
::iron::data::MaterialContext_obj::__boot();
::iron::data::ShaderContext_obj::__boot();
::iron::data::WorldData_obj::__boot();
::iron::math::Math_obj::__boot();
::iron::math::Quat_obj::__boot();
::iron::math::RayCaster_obj::__boot();
::iron::object::Animation_obj::__boot();
::iron::object::BoneAnimation_obj::__boot();
::iron::object::Object_obj::__boot();
::iron::object::CameraObject_obj::__boot();
::iron::object::LampObject_obj::__boot();
::iron::object::Transform_obj::__boot();
::kha::math::FastMatrix3_obj::__boot();
::iron::object::Uniforms_obj::__boot();
::iron::_hx_system::Input_obj::__boot();
::iron::_hx_system::Mouse_obj::__boot();
::iron::_hx_system::Pen_obj::__boot();
::iron::_hx_system::Keyboard_obj::__boot();
::iron::_hx_system::Gamepad_obj::__boot();
::iron::_hx_system::Time_obj::__boot();
::iron::_hx_system::Tween_obj::__boot();
::kha::Assets_obj::__boot();
::kha::_Color::Color_Impl__obj::__boot();
::kha::Scheduler_obj::__boot();
::kha::Shaders_obj::__boot();
::kha::System_obj::__boot();
::kha::SystemImpl_obj::__boot();
::kha::audio2::Audio1_obj::__boot();
::kha::audio2::ogg::tools::Crc32_obj::__boot();
::kha::audio2::ogg::vorbis::VorbisDecodeState_obj::__boot();
::kha::audio2::ogg::vorbis::VorbisTools_obj::__boot();
::kha::audio2::ogg::vorbis::data::Codebook_obj::__boot();
::kha::audio2::ogg::vorbis::data::Header_obj::__boot();
::kha::audio2::ogg::vorbis::data::PageFlag_obj::__boot();
::kha::audio2::ogg::vorbis::data::Setting_obj::__boot();
::kha::graphics2::Graphics_obj::__boot();
::kha::graphics2::truetype::StbTruetype_obj::__boot();
::kha::graphics4::ImageShaderPainter_obj::__boot();
::kha::graphics4::ColoredShaderPainter_obj::__boot();
::kha::graphics4::TextShaderPainter_obj::__boot();
::kha::input::Gamepad_obj::__boot();
::kha::input::Keyboard_obj::__boot();
::kha::input::Mouse_obj::__boot();
::kha::input::Sensor_obj::__boot();
::kha::internal::BytesBlob_obj::__boot();
::kha::math::Matrix3_obj::__boot();
::kha::math::Matrix4_obj::__boot();
::kha::math::Quaternion_obj::__boot();
::kha::network::ControllerBuilder_obj::__boot();
::kha::network::Session_obj::__boot();
::kha::network::SyncBuilder_obj::__boot();
::kha::vr::VrInterfaceEmulated_obj::__boot();
}

